### ISSUE TITLE
Add application to programs list on Windows

### ISSUE THREAD

**Issue by tech189** [Fusion/pngsource#10]
It would be great if you could register the program with the Installed apps list in Control Panel/Settings so that you could run the uninstaller without having to manually look for it in AppData!

**Comment by Fusion** [comment]
I see your point. I'll look up how to do that!

**Comment by Fusion** [comment]
I should add that the installer creates an "uninstall"  menu item in the start menu so you should not have to look for the app itself.

**Comment by Fusion** [comment]
Anyway this is almost done. Next release, soon.

**Comment by tech189** [comment]
Thanks! It would be best practice to keep Uninstall links out of the Start Menu because otherwise you get tons of identical shortcuts from different programs that all come up when you type "uninstall" into the search.

**Comment by Fusion** [comment]
Done. Sadly this does not give us a silent uninstall. Next time I guess. Anyway, the app can now be selected in the global uninstall list.
