### ISSUE TITLE
linux app crashes when trying to read file with embedded text

### ISSUE THREAD

**Issue by opheliagame** [Fusion/pngsource#6]
I tried to embed some text into a png but when trying to read this same file, the app crashes. Let me know how I can provide more useful information that might help with debugging this issue :)

**Comment by Fusion** [comment]
Hi. Well, this sucks.

If you could share this file with me, I will look into it. If you do not wish to share it publicly, you can email it to me: chris [at] zteo.com

If you cannot share it at all, then I will ask you to run the CLI version: if you run it with the `-v' flag, it may display the information we need to debug the issue.

**Comment by Fusion** [comment]
Hi @opheliagame any update?

**Comment by opheliagame** [comment]
so sorry for my late reply. [here](https://imgur.com/a/XdQycR1) is the image i tried to use. [here](https://pastebin.com/gct1zCwq) is the code that's embedded inside the png

**Comment by Fusion** [comment]
I believe this is fixed in v1.0.1
