### ISSUE TITLE
Error trying to install from dmg

### ISSUE THREAD

**Issue by sent-hil** [Fusion/pngsource#7]
Hi,

I found your repo from your comment on Hackernews. Downloaded the dmg from Github releases, but when I tried to open it this is the error I get:

![image](https://user-images.githubusercontent.com/164864/147862447-806cbaf9-4a2b-4926-87fb-942e386870de.png)

This is on the latest macbook M1pro, perhaps arm isn't supported?

EDIT: So yea most likely it's due to M1. https://github.com/karalabe/xgo doesn't support it.

**Comment by Fusion** [comment]
Actually, I developed this app in part on a Linux box and in part on my Mac M1.
Have you tried copying the app to your Applications folder and running it from there?

**Comment by Fusion** [comment]
Found the issue.
