### ISSUE TITLE
CLI tool produces no output

### ISSUE THREAD

**Issue by tech189** [Fusion/pngsource#8]
Can't get the CLI exe to output anything, just copied the exe from the cli zip, inside `dist\windows\cli`. GUI works fine!

```
apps/pngsource/current
❯ pngsource.exe

apps/pngsource/current
❯ pngsource.exe --help

apps/pngsource/current
❯ pngsource
```

**Comment by Fusion** [comment]
I can confirm. If this persists I'll try to build directly on Windows rather than use a cross-compiler.

**Comment by Fusion** [comment]
And I can also confirm that I messed up when building the binary. Please download this replacement exe while I prepare a new release... https://file.io/uqrOs3cyggbQ

**Comment by tech189** [comment]
Yay, can confirm that replacement exe works!

**Comment by Fusion** [comment]
Thanks. Released.
